### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by sbjshxbxijs** [IMPLabUniPr/movad#3]
when i run: python src/main.py --config cfgs/v4_2.yml --output output/v4_2/ --phase play --epoch 690

The terminal error is as follows: QFactoryLoader::QFactoryLoader() checking directory path "/home/ss/下载/enter/envs/movad_env/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Do you kow how to fix it? Thanks!

**Comment by hachreak** [comment]
Hi @sbjshxbxijs 
it looks like there is some library missing maybe for opencv-python or matplotlib (maybe `libxcb` library?).
Could you check [this](https://github.com/NVlabs/instant-ngp/discussions/300) or [this](https://github.com/opencv/opencv-python/issues/46) threads to see if you can find the best solution to fix the problem?
